//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/BattleSquares2/TestInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/BattleSquares2/TestInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @TestInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @TestInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""TestInput"",
    ""maps"": [
        {
            ""name"": ""MousePos"",
            ""id"": ""aef3da3c-a36b-4bf9-b544-af611c237bfd"",
            ""actions"": [
                {
                    ""name"": ""Call"",
                    ""type"": ""Value"",
                    ""id"": ""3726e1ad-7dae-4072-884c-5dfeedbdaa5f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""InteractSmall"",
                    ""type"": ""Button"",
                    ""id"": ""7c49409f-356c-4971-9cd7-750d3f623dbf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractBig"",
                    ""type"": ""Button"",
                    ""id"": ""cf644ed1-77af-4bcb-9d9d-ae3fc1b31eac"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SceneSwapTest"",
                    ""type"": ""Button"",
                    ""id"": ""9c53802b-1a46-44d7-aaa2-06600df96e7b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d3ef2030-9180-41be-b969-0251fd5a805f"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Call"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfa8045d-b45b-4473-9088-0c44787eb68e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractSmall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""394bc050-7f10-49c0-bfc8-f2cdabb6ea95"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractBig"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8f02018-aee8-4bad-89c0-dceb811dfa06"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SceneSwapTest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MousePos
        m_MousePos = asset.FindActionMap("MousePos", throwIfNotFound: true);
        m_MousePos_Call = m_MousePos.FindAction("Call", throwIfNotFound: true);
        m_MousePos_InteractSmall = m_MousePos.FindAction("InteractSmall", throwIfNotFound: true);
        m_MousePos_InteractBig = m_MousePos.FindAction("InteractBig", throwIfNotFound: true);
        m_MousePos_SceneSwapTest = m_MousePos.FindAction("SceneSwapTest", throwIfNotFound: true);
    }

    ~@TestInput()
    {
        UnityEngine.Debug.Assert(!m_MousePos.enabled, "This will cause a leak and performance issues, TestInput.MousePos.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MousePos
    private readonly InputActionMap m_MousePos;
    private List<IMousePosActions> m_MousePosActionsCallbackInterfaces = new List<IMousePosActions>();
    private readonly InputAction m_MousePos_Call;
    private readonly InputAction m_MousePos_InteractSmall;
    private readonly InputAction m_MousePos_InteractBig;
    private readonly InputAction m_MousePos_SceneSwapTest;
    /// <summary>
    /// Provides access to input actions defined in input action map "MousePos".
    /// </summary>
    public struct MousePosActions
    {
        private @TestInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MousePosActions(@TestInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "MousePos/Call".
        /// </summary>
        public InputAction @Call => m_Wrapper.m_MousePos_Call;
        /// <summary>
        /// Provides access to the underlying input action "MousePos/InteractSmall".
        /// </summary>
        public InputAction @InteractSmall => m_Wrapper.m_MousePos_InteractSmall;
        /// <summary>
        /// Provides access to the underlying input action "MousePos/InteractBig".
        /// </summary>
        public InputAction @InteractBig => m_Wrapper.m_MousePos_InteractBig;
        /// <summary>
        /// Provides access to the underlying input action "MousePos/SceneSwapTest".
        /// </summary>
        public InputAction @SceneSwapTest => m_Wrapper.m_MousePos_SceneSwapTest;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_MousePos; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MousePosActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MousePosActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MousePosActions" />
        public void AddCallbacks(IMousePosActions instance)
        {
            if (instance == null || m_Wrapper.m_MousePosActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MousePosActionsCallbackInterfaces.Add(instance);
            @Call.started += instance.OnCall;
            @Call.performed += instance.OnCall;
            @Call.canceled += instance.OnCall;
            @InteractSmall.started += instance.OnInteractSmall;
            @InteractSmall.performed += instance.OnInteractSmall;
            @InteractSmall.canceled += instance.OnInteractSmall;
            @InteractBig.started += instance.OnInteractBig;
            @InteractBig.performed += instance.OnInteractBig;
            @InteractBig.canceled += instance.OnInteractBig;
            @SceneSwapTest.started += instance.OnSceneSwapTest;
            @SceneSwapTest.performed += instance.OnSceneSwapTest;
            @SceneSwapTest.canceled += instance.OnSceneSwapTest;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MousePosActions" />
        private void UnregisterCallbacks(IMousePosActions instance)
        {
            @Call.started -= instance.OnCall;
            @Call.performed -= instance.OnCall;
            @Call.canceled -= instance.OnCall;
            @InteractSmall.started -= instance.OnInteractSmall;
            @InteractSmall.performed -= instance.OnInteractSmall;
            @InteractSmall.canceled -= instance.OnInteractSmall;
            @InteractBig.started -= instance.OnInteractBig;
            @InteractBig.performed -= instance.OnInteractBig;
            @InteractBig.canceled -= instance.OnInteractBig;
            @SceneSwapTest.started -= instance.OnSceneSwapTest;
            @SceneSwapTest.performed -= instance.OnSceneSwapTest;
            @SceneSwapTest.canceled -= instance.OnSceneSwapTest;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MousePosActions.UnregisterCallbacks(IMousePosActions)" />.
        /// </summary>
        /// <seealso cref="MousePosActions.UnregisterCallbacks(IMousePosActions)" />
        public void RemoveCallbacks(IMousePosActions instance)
        {
            if (m_Wrapper.m_MousePosActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MousePosActions.AddCallbacks(IMousePosActions)" />
        /// <seealso cref="MousePosActions.RemoveCallbacks(IMousePosActions)" />
        /// <seealso cref="MousePosActions.UnregisterCallbacks(IMousePosActions)" />
        public void SetCallbacks(IMousePosActions instance)
        {
            foreach (var item in m_Wrapper.m_MousePosActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MousePosActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MousePosActions" /> instance referencing this action map.
    /// </summary>
    public MousePosActions @MousePos => new MousePosActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MousePos" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MousePosActions.AddCallbacks(IMousePosActions)" />
    /// <seealso cref="MousePosActions.RemoveCallbacks(IMousePosActions)" />
    public interface IMousePosActions
    {
        /// <summary>
        /// Method invoked when associated input action "Call" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCall(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "InteractSmall" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnInteractSmall(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "InteractBig" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnInteractBig(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SceneSwapTest" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSceneSwapTest(InputAction.CallbackContext context);
    }
}
